name: workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # pour la mise à jour de l'onglet Security and quality
      contents: read # lire le code source
    steps:
      # Mettre les steps checkout et setup-java
    - name: Initialiser CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: java-kotlin

    - name: Construire avec Maven
      run: mvn-B clean package -DskipTests
    - name: Analyser avec CodeQL
      uses: github/codeql-action/analyze@v4

    - name: Construire avec Maven
      run: mvn -B clean verify -Dspring.profiles.active=test
    - name: Générer le site Maven
      run: mvn site
    - name: Publier le rapport Checkstyle
      uses: actions/upload-artifact@v4
      with:
        name: rapport-checkstyle
        path: target/site/


